spec:
  structures:
    - contentBlocks
    - firstContentBlocks
    - secondContentBlocks
  label: Divider
  description: A horizontal line to separate content
  icon: horizontal_rule
  tags:

blueprint:
  padding:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  padding:
    comment: The space on the top and bottom of the horizontal line.
    type: select
    options:
      values:
        - name: None
          id: none
        - name: Extra Small
          id: xs
        - name: Small
          id: sm
        - name: Medium
          id: md
        - name: Large
          id: lg
        - name: Extra Large
          id: xl
        - name: 2xl
          id: 2xl
        - name: 3xl
          id: 3xl
