spec:
  structures:
    - content_blocks
  label: Cluster
  description: "Responsive, centered cluster with configurable sizing."
  icon: squares-2x2
  tags: []

blueprint:
  minItemWidth: 200
  maxItemWidth: 320
  verticalAlignment: "start"
  equalWidth: true
  items:
    - contentBlocks:

preview:

_inputs:
  minItemWidth:
    comment: The minimum width for each cluster item in pixels.
    type: number
  maxItemWidth:
    comment: The maximum width for each cluster item in pixels.
    type: number
  verticalAlignment:
    comment: The vertical alignment of cluster items.
    type: select
    options:
      values:
        - start
        - center
        - end
        - stretch
  equalWidth:
    comment: Whether items should have equal widths (true) or intrinsic widths based on content (false).
    type: boolean
  items:
    comment: Array of cluster items, each containing content blocks to render.
    type: array
    _inputs:
      contentBlocks:
        comment: Content blocks to render within this cluster item.
        type: array
