spec:
  structures:
    - formBlocks
  label: Select
  description: "A dropdown select field with an optional label."
  icon: rectangle
  tags: []

blueprint:
  label:
  name:
  options:
    - value: "option1"
      label: "Option 1"
    - value: "option2"
      label: "Option 2"
    - value: "option3"
      label: "Option 3"
  placeholder:
  required: false
  value:

preview:

_inputs:
  label:
    type: text
    comment: The label text for the select field.
  name:
    type: text
    comment: The name attribute for the select field.
  options:
    type: blocks
    comment: Array of select options with value and label.
  placeholder:
    type: text
    comment: Placeholder text for the select field.
  required:
    type: switch
    comment: Whether the field is required.
  value:
    type: text
    comment: The default selected value.
